version: '3'
services:
  mongo:
    container_name: easybooks-mongo
    image: mongo
    restart: always
    ports:
      - 27117:27017
  api:
    container_name: easybooks-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.aws
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
