version: '3'
services:
  mongo:
    container_name: easybooks-mongo
    image: mongo
    restart: always
    ports:
      - 27117:27017
  api:
    container_name: easybooks-api
    restart: always
    build: .
    ports:
      - 3030:3030
    links:
      - mongo
    depends_on:
      - mongo
